apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "assignment2"
        service: "database"
    spec:
      containers:
        - name: influxdb
          image: "influxdb"