apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: databaseaccess
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "assignment2"
        service: "databaseaccess"
    spec:
      containers:
        - name: databaseaccess
          image: "padarighj/ddms-assignment2-databaseaccess:latest"
       