apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "assignment2"
        service: "webserver"
    spec:
      containers:
        - name: webserver
          image: "padarighj/ddms-assignment2-webserver:latest"
         